### ISSUE TITLE
Exercise 2: Implement the sandwich and library database schema and queries

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/MySQL#2]
https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise2a.sql
http://dl.dropbox.com/u/628209/exercises/mysql/sandwich.pdf 

https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise2b.sql
http://dl.dropbox.com/u/628209/exercises/mysql/multibranch_library.pdf

Please submit mysql schema and queries for both the exercises described in the PDFs above. Please submit mysql schema and queries for both the exercises described in the PDFs above.

**Comment by osifoanosike** [comment]
Please confirm and correct the dropbox link

**Comment by OkwufuluezeD** [comment]
Done.

**Comment by DOkwufulueze** [comment]
Link confirmed and modifications done.

**Comment by osifoanosike** [comment]
Update the links to the exercises in the description.

**Comment by DOkwufulueze** [comment]
Update done.
