### ISSUE TITLE
Exercise 4: Implement Articles Database

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/MySQL#4]
https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise4.sql

Design a table structure for following conditions:A user can write many articles. Each written article will fall under one category. Remember that many articles can be written under same category.The users can be of two types viz. admin or normal. A user can post multiple comments on an article.Now write queries for:
manage categories, articles, comments, and users
select all articles whose author's name is user3 (Do this exercise using variable also).
For all the articles being selected above, select all the articles and also the comments associated with those articles in a single query (Do this using subquery also)
Write a query to select all articles which do not have any comments (Do using subquery also)
Write a query to select article which has maximum comments
Write a query to select article which does not have more than one comment by the same user ( do this using left join and group by ).

**Comment by osifoanosike** [comment]
Why do u have nullable ID fields?

**Comment by osifoanosike** [comment]
- Do we need ON UPDATE CASCADE ? If Yes Why?
- https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise4.sql#L148
- Why use `IN` clause here?
- https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise4.sql#L188
  Run this query for a senario of 3 articles that have the highest nos of comments.

**Comment by DOkwufulueze** [comment]
Unnecessary Update Cascading removed.

IN clause is needed for perhaps, the returned table might contain more than one row since username isn't a PRIMARY KEY as required by the exercise.

Query now covers more than one case if necessary.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise4.sql#L30
You can use a better name for that field. Since the table name is 'articles'

**Comment by DOkwufulueze** [comment]
Naming convention observed.
