### ISSUE TITLE
Exercise 6: Campaign email subscribers

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/MySQL#6]
https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise6.sql

We ran a campaign on a website, asking people to submit their email address, their city and phone number.The data was collected in a csv format - The file is here... http://dl.dropbox.com/First import this csv data into a mysql datbase.From the database, we need to find the following information by writing a single sql statement for each
What all cities did people respond from
How many people responded from each city
Which city were the maximum respondents from?
What all email domains did people respond from ?
Which is the most popular email domain among the respondents ?

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/MySQL/blob/master/Exercise6.sql#L70
Look into SUBSTRING_INDEX, This should be a more optimal option.

**Comment by DOkwufulueze** [comment]
SUBSTRING_INDEX used instead of the less optimal RIGHT.
